/*
 * Generated by JasperReports - 2/2/15 10:14 AM
 */
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.fill.*;

import java.util.*;
import java.math.*;
import java.text.*;
import java.io.*;
import java.net.*;



/**
 *
 */
class Renew_1422900851742_6662 extends JREvaluator
{


    /**
     *
     */
    private JRFillParameter parameter_IS_IGNORE_PAGINATION = null;
    private JRFillParameter parameter_REPORT_CONNECTION = null;
    private JRFillParameter parameter_REPORT_LOCALE = null;
    private JRFillParameter parameter_REPORT_TIME_ZONE = null;
    private JRFillParameter parameter_REPORT_TEMPLATES = null;
    private JRFillParameter parameter_REPORT_MAX_COUNT = null;
    private JRFillParameter parameter_REPORT_SCRIPTLET = null;
    private JRFillParameter parameter_mtop_no = null;
    private JRFillParameter parameter_REPORT_FILE_RESOLVER = null;
    private JRFillParameter parameter_REPORT_FORMAT_FACTORY = null;
    private JRFillParameter parameter_REPORT_PARAMETERS_MAP = null;
    private JRFillParameter parameter_REPORT_RESOURCE_BUNDLE = null;
    private JRFillParameter parameter_REPORT_DATA_SOURCE = null;
    private JRFillParameter parameter_REPORT_CLASS_LOADER = null;
    private JRFillParameter parameter_REPORT_URL_HANDLER_FACTORY = null;
    private JRFillParameter parameter_REPORT_VIRTUALIZER = null;
    private JRFillField field_address = null;
    private JRFillField field_mayors = null;
    private JRFillField field_reg_no = null;
    private JRFillField field_mtop_year = null;
    private JRFillField field_city_ad = null;
    private JRFillField field_or_no = null;
    private JRFillField field_MTOP_NO = null;
    private JRFillField field_released_date = null;
    private JRFillField field_mayors_permit_fee = null;
    private JRFillField field_plate_no = null;
    private JRFillField field_chassis_no = null;
    private JRFillField field_paid = null;
    private JRFillField field_head1 = null;
    private JRFillField field_stick = null;
    private JRFillField field_fullname = null;
    private JRFillField field_motor_no = null;
    private JRFillField field_exp = null;
    private JRFillField field_make = null;
    private JRFillField field_status = null;
    private JRFillVariable variable_PAGE_NUMBER = null;
    private JRFillVariable variable_COLUMN_NUMBER = null;
    private JRFillVariable variable_REPORT_COUNT = null;
    private JRFillVariable variable_PAGE_COUNT = null;
    private JRFillVariable variable_COLUMN_COUNT = null;


    /**
     *
     */
    void customizedInit(
        Map pm,
        Map fm,
        Map vm
        )
    {
        initParams(pm);
        initFields(fm);
        initVars(vm);
    }


    /**
     *
     */
    void initParams(Map pm)
    {
        parameter_IS_IGNORE_PAGINATION = (JRFillParameter)pm.get("IS_IGNORE_PAGINATION");
        parameter_REPORT_CONNECTION = (JRFillParameter)pm.get("REPORT_CONNECTION");
        parameter_REPORT_LOCALE = (JRFillParameter)pm.get("REPORT_LOCALE");
        parameter_REPORT_TIME_ZONE = (JRFillParameter)pm.get("REPORT_TIME_ZONE");
        parameter_REPORT_TEMPLATES = (JRFillParameter)pm.get("REPORT_TEMPLATES");
        parameter_REPORT_MAX_COUNT = (JRFillParameter)pm.get("REPORT_MAX_COUNT");
        parameter_REPORT_SCRIPTLET = (JRFillParameter)pm.get("REPORT_SCRIPTLET");
        parameter_mtop_no = (JRFillParameter)pm.get("mtop_no");
        parameter_REPORT_FILE_RESOLVER = (JRFillParameter)pm.get("REPORT_FILE_RESOLVER");
        parameter_REPORT_FORMAT_FACTORY = (JRFillParameter)pm.get("REPORT_FORMAT_FACTORY");
        parameter_REPORT_PARAMETERS_MAP = (JRFillParameter)pm.get("REPORT_PARAMETERS_MAP");
        parameter_REPORT_RESOURCE_BUNDLE = (JRFillParameter)pm.get("REPORT_RESOURCE_BUNDLE");
        parameter_REPORT_DATA_SOURCE = (JRFillParameter)pm.get("REPORT_DATA_SOURCE");
        parameter_REPORT_CLASS_LOADER = (JRFillParameter)pm.get("REPORT_CLASS_LOADER");
        parameter_REPORT_URL_HANDLER_FACTORY = (JRFillParameter)pm.get("REPORT_URL_HANDLER_FACTORY");
        parameter_REPORT_VIRTUALIZER = (JRFillParameter)pm.get("REPORT_VIRTUALIZER");
    }


    /**
     *
     */
    void initFields(Map fm)
    {
        field_address = (JRFillField)fm.get("address");
        field_mayors = (JRFillField)fm.get("mayors");
        field_reg_no = (JRFillField)fm.get("reg_no");
        field_mtop_year = (JRFillField)fm.get("mtop_year");
        field_city_ad = (JRFillField)fm.get("city_ad");
        field_or_no = (JRFillField)fm.get("or_no");
        field_MTOP_NO = (JRFillField)fm.get("MTOP_NO");
        field_released_date = (JRFillField)fm.get("released_date");
        field_mayors_permit_fee = (JRFillField)fm.get("mayors_permit_fee");
        field_plate_no = (JRFillField)fm.get("plate_no");
        field_chassis_no = (JRFillField)fm.get("chassis_no");
        field_paid = (JRFillField)fm.get("paid");
        field_head1 = (JRFillField)fm.get("head1");
        field_stick = (JRFillField)fm.get("stick");
        field_fullname = (JRFillField)fm.get("fullname");
        field_motor_no = (JRFillField)fm.get("motor_no");
        field_exp = (JRFillField)fm.get("exp");
        field_make = (JRFillField)fm.get("make");
        field_status = (JRFillField)fm.get("status");
    }


    /**
     *
     */
    void initVars(Map vm)
    {
        variable_PAGE_NUMBER = (JRFillVariable)vm.get("PAGE_NUMBER");
        variable_COLUMN_NUMBER = (JRFillVariable)vm.get("COLUMN_NUMBER");
        variable_REPORT_COUNT = (JRFillVariable)vm.get("REPORT_COUNT");
        variable_PAGE_COUNT = (JRFillVariable)vm.get("PAGE_COUNT");
        variable_COLUMN_COUNT = (JRFillVariable)vm.get("COLUMN_COUNT");
    }


    /**
     *
     */
    Object evaluate(int id)
    {
        Object value = null;

        if (id == 0)
        {
            value = (java.lang.String)(null);
        }
        else if (id == 1)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 2)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 3)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 4)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 5)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 6)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 7)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 8)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 9)
        {
            value = (java.lang.String)(((java.lang.String)field_fullname.getValue()));
        }
        else if (id == 10)
        {
            value = (java.lang.String)(((java.lang.String)field_chassis_no.getValue()));
        }
        else if (id == 11)
        {
            value = (java.lang.String)(((java.lang.String)field_plate_no.getValue()));
        }
        else if (id == 12)
        {
            value = (java.lang.String)(((java.lang.String)field_make.getValue()));
        }
        else if (id == 13)
        {
            value = (java.lang.String)(((java.lang.String)field_address.getValue()));
        }
        else if (id == 14)
        {
            value = (java.lang.String)(((java.lang.String)field_exp.getValue()));
        }
        else if (id == 15)
        {
            value = (java.lang.String)(((java.lang.String)field_city_ad.getValue()));
        }
        else if (id == 16)
        {
            value = (java.lang.String)(((java.lang.String)field_or_no.getValue()));
        }
        else if (id == 17)
        {
            value = (java.lang.String)(((java.lang.String)field_mayors_permit_fee.getValue()));
        }
        else if (id == 18)
        {
            value = (java.lang.String)(((java.lang.String)field_paid.getValue()));
        }
        else if (id == 19)
        {
            value = (java.lang.String)(new java.util.Date());
        }
        else if (id == 20)
        {
            value = (java.lang.String)(((java.lang.String)field_mayors.getValue()));
        }
        else if (id == 21)
        {
            value = (java.lang.String)(((java.lang.String)field_stick.getValue()));
        }
        else if (id == 22)
        {
            value = (java.lang.String)(new java.util.Date().format('yyyy').toString());
        }
        else if (id == 23)
        {
            value = (java.lang.String)(((java.lang.String)field_mtop_year.getValue()));
        }
        else if (id == 24)
        {
            value = (java.lang.String)(((java.lang.String)field_head1.getValue()));
        }

        return value;
    }


    /**
     *
     */
    Object evaluateOld(int id)
    {
        Object value = null;

        if (id == 0)
        {
            value = (java.lang.String)(null);
        }
        else if (id == 1)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 2)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 3)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 4)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 5)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 6)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 7)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 8)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 9)
        {
            value = (java.lang.String)(((java.lang.String)field_fullname.getOldValue()));
        }
        else if (id == 10)
        {
            value = (java.lang.String)(((java.lang.String)field_chassis_no.getOldValue()));
        }
        else if (id == 11)
        {
            value = (java.lang.String)(((java.lang.String)field_plate_no.getOldValue()));
        }
        else if (id == 12)
        {
            value = (java.lang.String)(((java.lang.String)field_make.getOldValue()));
        }
        else if (id == 13)
        {
            value = (java.lang.String)(((java.lang.String)field_address.getOldValue()));
        }
        else if (id == 14)
        {
            value = (java.lang.String)(((java.lang.String)field_exp.getOldValue()));
        }
        else if (id == 15)
        {
            value = (java.lang.String)(((java.lang.String)field_city_ad.getOldValue()));
        }
        else if (id == 16)
        {
            value = (java.lang.String)(((java.lang.String)field_or_no.getOldValue()));
        }
        else if (id == 17)
        {
            value = (java.lang.String)(((java.lang.String)field_mayors_permit_fee.getOldValue()));
        }
        else if (id == 18)
        {
            value = (java.lang.String)(((java.lang.String)field_paid.getOldValue()));
        }
        else if (id == 19)
        {
            value = (java.lang.String)(new java.util.Date());
        }
        else if (id == 20)
        {
            value = (java.lang.String)(((java.lang.String)field_mayors.getOldValue()));
        }
        else if (id == 21)
        {
            value = (java.lang.String)(((java.lang.String)field_stick.getOldValue()));
        }
        else if (id == 22)
        {
            value = (java.lang.String)(new java.util.Date().format('yyyy').toString());
        }
        else if (id == 23)
        {
            value = (java.lang.String)(((java.lang.String)field_mtop_year.getOldValue()));
        }
        else if (id == 24)
        {
            value = (java.lang.String)(((java.lang.String)field_head1.getOldValue()));
        }

        return value;
    }


    /**
     *
     */
    Object evaluateEstimated(int id)
    {
        Object value = null;

        if (id == 0)
        {
            value = (java.lang.String)(null);
        }
        else if (id == 1)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 2)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 3)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 4)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 5)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 6)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 7)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 8)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 9)
        {
            value = (java.lang.String)(((java.lang.String)field_fullname.getValue()));
        }
        else if (id == 10)
        {
            value = (java.lang.String)(((java.lang.String)field_chassis_no.getValue()));
        }
        else if (id == 11)
        {
            value = (java.lang.String)(((java.lang.String)field_plate_no.getValue()));
        }
        else if (id == 12)
        {
            value = (java.lang.String)(((java.lang.String)field_make.getValue()));
        }
        else if (id == 13)
        {
            value = (java.lang.String)(((java.lang.String)field_address.getValue()));
        }
        else if (id == 14)
        {
            value = (java.lang.String)(((java.lang.String)field_exp.getValue()));
        }
        else if (id == 15)
        {
            value = (java.lang.String)(((java.lang.String)field_city_ad.getValue()));
        }
        else if (id == 16)
        {
            value = (java.lang.String)(((java.lang.String)field_or_no.getValue()));
        }
        else if (id == 17)
        {
            value = (java.lang.String)(((java.lang.String)field_mayors_permit_fee.getValue()));
        }
        else if (id == 18)
        {
            value = (java.lang.String)(((java.lang.String)field_paid.getValue()));
        }
        else if (id == 19)
        {
            value = (java.lang.String)(new java.util.Date());
        }
        else if (id == 20)
        {
            value = (java.lang.String)(((java.lang.String)field_mayors.getValue()));
        }
        else if (id == 21)
        {
            value = (java.lang.String)(((java.lang.String)field_stick.getValue()));
        }
        else if (id == 22)
        {
            value = (java.lang.String)(new java.util.Date().format('yyyy').toString());
        }
        else if (id == 23)
        {
            value = (java.lang.String)(((java.lang.String)field_mtop_year.getValue()));
        }
        else if (id == 24)
        {
            value = (java.lang.String)(((java.lang.String)field_head1.getValue()));
        }

        return value;
    }


}
